- modules:
  - name: [Data.Set]
    as: Set
  - name: [Data.Map, Data.Map.Strict]
    as: Map

- error: {lhs: "mapM f xs", rhs: traverse f xs}
- error: {lhs: "forM x f", rhs: for x f}
- error: {lhs: "mapM_ f x", rhs: traverse_ f x}
- error: {lhs: "forM_ x f", rhs: for_ x f}
- warning: {lhs: "mappend x y", rhs: x <> y}
- warning: {lhs: "fmap f ask", rhs: asks f}
- warning: {lhs: "f <$> ask", rhs: asks f}

- ignore: {name: "Reduce duplication"}
- ignore: {name: "Use camelCase"}
- ignore: {name: "Parse error"}
